#!/usr/bin/env python3

def intersection(l1, l2):
    # https://www.cuemath.com/geometry/intersection-of-two-lines/
    # I bet linear algebra would actually be faster...
    # ((B1C2 - B2C1)/(A1B2 - A2B1), (C1A2 - C2A1)/(A1B2 - A2B1))
    A1, B1, C1 = l1
    A2, B2, C2 = l2

    num1 = B1*C2 - B2*C1
    num2 = C1*A2 - C2*A1
    denom = A1*B2 - A2*B1

    # lines are parallel
    if denom == 0:
        return None

    xy = [num1/float(denom), num2/float(denom)]
    return xy

# general form of a line equation:
#
#   Ax + By = C
#
# point/slope form:
#
#   y = mx + b
#
#  By = -Ax + C
#   y = (-A/B)x + C/B
#
# therefore,
#
#   A=-1, B=1, C=0  -> m=1, b=0 
#   A=1, B=1, C=0  -> m=-1, b=0 
#
# these two lines should obviously intersect
# at (0, 0)
l1 = [-1, 1, 0]
l2 = [1, 1, 0]
print(l1)
print(l2)
print(intersection(l1, l2))
      
# now move both lines up by 1
#
#   A=-1, B=1, C=1  -> m=1, b=1
#   A=1, B=1, C=1  -> m=-1, b=1 
#
# these two lines should obviously intersect
# at (1, 1)....but nope.
l1 = [-1, 1, 1]
l2 = [1, 1, 1]
print(l1)
print(l2)
print(intersection(l1, l2))
